# Generated by Django 5.2 on 2026-04-25 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='is_signed',
            field=models.BooleanField(default=False, help_text='Документ подписан ЭЦП'),
        ),
        migrations.AddField(
            model_name='resolution',
            name='signature_data',
            field=models.TextField(blank=True, help_text='Данные цифровой подписи'),
        ),
        migrations.AddField(
            model_name='resolution',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolution',
            name='signed_by',
            field=models.ForeignKey(blank=True, help_text='Лицо, подписавшее документ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_resolutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
