# Generated by Django 5.2 on 2026-04-25 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_resolution_is_signed_resolution_signature_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Обновление'), ('DELETE', 'Удаление'), ('SIGN', 'Подпись'), ('APPROVE', 'Одобрение'), ('REJECT', 'Отклонение'), ('EXPORT', 'Экспорт'), ('PRINT', 'Печать')], max_length=20)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('object_str', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог аудита',
                'verbose_name_plural': 'Логи аудита',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='documents_a_timesta_0c4e02_idx'), models.Index(fields=['user'], name='documents_a_user_id_606c2f_idx'), models.Index(fields=['object_type', 'object_id'], name='documents_a_object__a6ebff_idx')],
            },
        ),
    ]
