# Generated by Django 5.2 on 2026-04-27 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='destination_department',
            field=models.ForeignKey(blank=True, help_text='Отдел-получатель', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_documents', to='documents.department'),
        ),
        migrations.AddField(
            model_name='document',
            name='destination_org',
            field=models.CharField(blank=True, help_text='Государственное учреждение-получатель', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='destination_person',
            field=models.ForeignKey(blank=True, help_text='Лицо, ответственное за обработку', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_appeals', to=settings.AUTH_USER_MODEL),
        ),
    ]
