# Generated by Django 5.2 on 2026-04-27 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_destination_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('institution_type', models.CharField(choices=[('ministry', 'Министерство'), ('agency', 'Агентство'), ('committee', 'Комитет'), ('hokimiyat', 'Хокимият'), ('other', 'Другое учреждение')], max_length=20)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Государственное учреждение',
                'verbose_name_plural': 'Государственные учреждения',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['institution', 'name'], 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('chancellery', 'Канцелярия'), ('hr', 'Отдел кадров'), ('legal', 'Юридический отдел'), ('finance', 'Финансовый отдел'), ('it', 'Отдел ИКТ'), ('press', 'Пресс-служба'), ('appeals', 'Отдел по работе с обращениями'), ('other', 'Другой отдел')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='acceptance_status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', help_text='Статус приема входящего документа', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='accepted_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, принявший документ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Причина отклонения документа'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='documents.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('code', 'institution')},
        ),
    ]
