# Generated by Django 5.2 on 2026-04-29 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_institution_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenthistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'История документа', 'verbose_name_plural': 'История документов'},
        ),
        migrations.RenameField(
            model_name='documenthistory',
            old_name='changed_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='documenthistory',
            old_name='note',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='documenthistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='documenthistory',
            name='new_status',
        ),
        migrations.RemoveField(
            model_name='documenthistory',
            name='old_status',
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('REGISTERED', 'Зарегистрирован'), ('SENT', 'Отправлен'), ('RECEIVED', 'Получен'), ('ACCEPTED', 'Принят'), ('REJECTED', 'Отклонен'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Завершен')], default='CREATED', max_length=20),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
