# Generated by Django 5.2 on 2026-05-03 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_documenthistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_file', models.FileField(blank=True, help_text='Сопроводительный документ', null=True, upload_to='transfers/%Y/%m/')),
                ('transfer_note', models.TextField(blank=True, help_text='Примечание к передаче')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', help_text='Статус передачи', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Причина отклонения')),
                ('accepted_by', models.ForeignKey(blank=True, help_text='Руководитель, принявший документ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_transfers', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Документ для передачи', on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='documents.document')),
                ('from_department', models.ForeignKey(help_text='Отдел отправителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transfers', to='documents.department')),
                ('from_user', models.ForeignKey(help_text='Руководитель-отправитель', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_department', models.ForeignKey(help_text='Отдел получателя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='documents.department')),
                ('to_user', models.ForeignKey(help_text='Руководитель-получатель', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Передача документа',
                'verbose_name_plural': 'Передачи документов',
                'ordering': ['-created_at'],
            },
        ),
    ]
